/*******************************************************************************
 * This file is part of "Patrick's Programming Library", Version 8 (PPLIB).
 * Web: https://github.com/pfedick/pplib
 *******************************************************************************
 * Copyright (c) 2026, Patrick Fedick <patrick@pfp.de>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *    1. Redistributions of source code must retain the above copyright notice,
 *       this list of conditions and the following disclaimer.
 *    2. Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER AND CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGE.
 *******************************************************************************/
#include <string.h>
#include <pplib/core/fileobject.h>
#include <pplib/core/file.h>
#include <pplib/core/functions.h>
#include <pplib/version.h>
#include <pplib/types/array.h>
#include <pplib/types/bytearray.h>
#include <pplib/grafix/image.h>
#include <pplib/grafix/grafix.h>
#include <pplib/grafix/imagefilter.h>

namespace pplib::grafix
{

/*!\class ImageFilter_PPM
 * \ingroup PPLGroupGrafik
 * \brief Import-/Export-Filter für PPM-Dateien
 */

ImageFilter_PPM::ImageFilter_PPM()
{
    // SaveAsASCII=false;
}

ImageFilter_PPM::~ImageFilter_PPM()
{
}

bool ImageFilter_PPM::ident(FileObject& file, IMAGE& img) noexcept
{
    try {
        String line;
        file.seek(0);
        file.gets(line, 64);
        if (line.left(3) == "P6\n") { // Ja, ist ein PPM
            file.gets(line, 64);      // Breite und Hoehe holen
            line.trim();
            while (line[0] == '#') { // Es koennte sein, dass hier Kommentare drin sind
                file.gets(line, 64); // Breite und Hoehe holen
                line.trim();
            }
            Array a;
            a.explode(line, " ");
            img.width = a.get(0).toInt();
            img.height = a.get(1).toInt();
            // file->Gets(tmpc,64);			// Farbtiefe holen, normalerweise 255
            img.bitdepth = 24;
            img.colors = 0x1000000;
            img.pitch = 3 * img.width;
            img.format = RGBFormat::X8R8G8B8;
            return 1;
        }
    }
    catch (...) {
        return 0;
    }
    return 0;
}

void ImageFilter_PPM::load(FileObject& file, Drawable& surface, IMAGE& img)
{
    String line;
    file.seek(0);
    file.gets(line, 64);
    if (line.left(3) != "P6\n") throw UnknownImageFormatException();
    file.gets(line, 64); // Breite und Hoehe holen
    line.trim();
    while (line[0] == '#') { // Es koennte sein, dass hier Kommentare drin sind
        file.gets(line, 64);
        line.trim();
    }
    Array a;
    a.explode(line, " ");
    img.width = a.get(0).toInt();
    img.height = a.get(1).toInt();
    file.gets(line, 64); // Farbtiefe holen, normalerweise 255
    // int farbtiefe;
    // farbtiefe=line.toInt();

    int x, y;
    uint8_t r, g, b;
    uint64_t pp = file.tell();
    const char* adresse;
    for (y = 0; y < surface.height(); y++) {
        adresse = file.map(pp, img.pitch); // Zeile fuer Zeile einlesen
        pp += img.pitch;
        for (x = 0; x < surface.width(); x++) {
            r = adresse[x * 3];
            g = adresse[x * 3 + 1];
            b = adresse[x * 3 + 2];
            surface.putPixel(x, y, Color(r, g, b));
        }
    }
}

void ImageFilter_PPM::saveFile(const String& filename, const Drawable& surface, bool asAscii) const
{
    File ff;
    ff.open(filename, File::FileMode::WRITE);
    save(surface, ff);
}

void ImageFilter_PPM::save(const Drawable& surface, FileObject& file, bool asAscii) const
{
    Color farbe;
    // int haupt,unter,build;

    if (surface.rgbformat().bitdepth() > 8) {
        if (asAscii == false)
            file.puts("P6\n");
        else
            file.puts("P3\n");
        file.putsf("# Generated by PPL %u.%u.%u\n", PPLIB_VERSION_MAJOR, PPLIB_VERSION_MINOR, PPLIB_VERSION_BUILD);
        file.putsf("# %s\n", PPLIB_COPYRIGHT);
        file.putsf("%d %d\n", surface.width(), surface.height());
        file.putsf("%d\n", 255);
        int c = 0;
        for (int y = 0; y < surface.height(); y++) {
            for (int x = 0; x < surface.width(); x++) {
                farbe = surface.getPixel(x, y);
                uint8_t r = (uint8_t)farbe.red();
                uint8_t g = (uint8_t)farbe.green();
                uint8_t b = (uint8_t)farbe.blue();
                if (asAscii == false) {
                    file.write((char*)&r, 1);
                    file.write((char*)&g, 1);
                    file.write((char*)&b, 1);
                } else {
                    file.putsf("%u %u %u ", r, g, b);
                    c++;
                    if (c > 7) {
                        file.puts("\n");
                        c = 0;
                    }
                }
            }
        }
        if (asAscii == true) {
            file.puts("\n");
        }
        return;
    }
    throw UnsupportedFeatureException("ImageFilter_PPM::save unsupported bitdepth");
}

} // namespace pplib::grafix