#!/bin/sh

case "`uname -s`" in
	FreeBSD)
		ACLOCAL=aclocal
		AUTOMAKE=automake
		AUTOCONF=autoconf
		;;
	*)
		ACLOCAL=aclocal
		AUTOMAKE=automake
		AUTOCONF=autoconf
		;;
		
esac


sh genMakefile.in
$ACLOCAL
$AUTOMAKE --add-missing
$AUTOCONF
